/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_minebarteksa_sonos_jni_stdio */

#ifndef _Included_com_minebarteksa_sonos_jni_stdio
#define _Included_com_minebarteksa_sonos_jni_stdio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_minebarteksa_sonos_jni_stdio
 * Method:    jprintf
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_minebarteksa_sonos_jni_stdio_jprintf
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
